import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../globals.css";
import Header from "./components/layout/header";
import Footer from "./components/layout/footer";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"]
});



export const metadata: Metadata = {
  title: "Hospital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable}  antialiased container mx-auto w-316`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
